package com.example.ui

enum class AppLanguage(val code: String) {
    EN("en"),
    RU("ru")
}

object LanguageHelper {
    private val enStrings = mapOf(
        "languageTitle" to "Language/Язык",
        "languageSub" to "Choose your language\nВыберите язык",
        "languageNote" to "Note: The date language is determined by the language on the device.\nВажно: Дата будет отображаться на языке устройства.",
        "btnEnglish" to "English",
        "btnRussian" to "Русский",
        "btnSettings" to "Settings",
        "btnSpend" to "Spend",
        "btnTopUp" to "Top up",
        "settingsTitle" to "Settings",
        "setGoal" to "Set goal",
        "countMoney" to "Count money",
        "saveHistory" to "Save history",
        "loadHistory" to "Load history",
        "changeLanguage" to "Change language",
        "aboutApp" to "About app",
        "exit" to "Exit",
        "clearHistory" to "Clear history",
        "clearHistoryConfirm" to "Are you sure you want to clear all history? This action cannot be undone.",
        "cancelTxConfirm" to "Are you sure you want to cancel this operation?",
        "customCurrency" to "Custom currency",
        "customCurrencySymbolLabel" to "Currency symbol (e.g. $, €, £)",
        "customCurrencyToggle" to "Enable manual currency",
        "goalUnset" to "Set goal and money",
        "toTheGoal" to "to the goal",
        "amount" to "Amount",
        "reason" to "Reason",
        "aboutAppTitle" to "About Kopilka",
        "aboutAppText" to "Kopilka is a simple budget assistant to track your incomes and expenses.\n\nCreated by Artyomka628 - github.com/artyomka628",
        "inputGoal" to "Goal Amount",
        "inputInitial" to "Current Balance",
        "invalidAmount" to "Please enter a valid amount",
        "amountTooLarge" to "The amount is too large (max: 1,000,000,000)",
        "success" to "Success!",
        "errorSaving" to "Error saving history",
        "errorLoading" to "Error loading history",
        "historySaved" to "History exported successfully",
        "historyLoaded" to "History imported successfully",
        "historyEmpty" to "Transaction history is empty",
        "enterReason" to "Enter description",
        "confirm" to "Confirm",
        "cancel" to "Cancel",
        "statsResetFrequency" to "Statistics Reset Interval",
        "btnResetStatsNow" to "Reset Statistics Now",
        "resetManual" to "Manually",
        "resetDaily" to "Daily",
        "resetWeekly" to "Weekly",
        "resetMonthly" to "Monthly",
        "hideGoalProgress" to "Hide Goal Progress",
        "showMoreColors" to "More Colors",
        "showLessColors" to "Fewer Colors",
        "themeTitle" to "App Theme Color",
        "themeViolet" to "Violet (Default)",
        "themeTeal" to "Teal",
        "themeAmber" to "Amber",
        "themeEmerald" to "Emerald",
        "themeRose" to "Rose",
        "themeBlue" to "Ice Blue",
        "themeRed" to "Red",
        "themeIndigo" to "Indigo",
        "themeOrange" to "Orange",
        "themePurple" to "Purple",
        "themeCyan" to "Cyan",
        "themeLime" to "Lime",
        "themePeach" to "Peach",
        "themeMint" to "Mint",
        "themeLavender" to "Lavender",
        "themeSky" to "Sky Blue",
        "themeMagenta" to "Magenta",
        "themeGold" to "Gold",
        "themeSapphire" to "Sapphire",
        "themeBronze" to "Bronze",
        "themeMaterialYou" to "Material You (System)",
        "themeCustom" to "Custom Color",
        "customColorPicker" to "Color Picker (RGB)",
        "customAppIconSettings" to "App Launcher Icon Settings",
        "launcherIconColor" to "Home Screen Icon Color",
        "matchAppTheme" to "Match App Theme",
        "matchSystem" to "Match System (Material You)",
        "appIconSymbolTitle" to "App Icon Currency Symbol",
        "appIconSymbolDesc" to "Custom symbol displayed in the app's top corner.",
        "applyIconBtn" to "Apply App Icon",
        "applyIconSuccess" to "Icon applied successfully! Launcher updated.",
        "appVersion" to "App Version",
        "checkForUpdates" to "Check for Updates",
        "updateAvailable" to "Update Available!",
        "upToDate" to "You have the latest version!",
        "downloadUpdate" to "Download Update",
        "checkingUpdates" to "Checking for updates...",
        "errorCheckingUpdates" to "Error checking for updates"
    )

    private val ruStrings = mapOf(
        "languageTitle" to "Language/Язык",
        "languageSub" to "Choose your language\nВыберите язык",
        "languageNote" to "Note: The date language is determined by the language on the device.\nВажно: Дата будет отображаться на языке устройства.",
        "btnEnglish" to "English",
        "btnRussian" to "Русский",
        "btnSettings" to "Настройки",
        "btnSpend" to "Расход",
        "btnTopUp" to "Доход",
        "settingsTitle" to "Настройки",
        "setGoal" to "Задать цель",
        "countMoney" to "Рассчитать деньги",
        "saveHistory" to "Сохранить историю",
        "loadHistory" to "Загрузить историю",
        "changeLanguage" to "Сменить язык",
        "aboutApp" to "О приложении",
        "exit" to "Выход",
        "clearHistory" to "Очистить историю",
        "clearHistoryConfirm" to "Вы уверены, что хотите очистить всю историю? Это действие нельзя отменить.",
        "cancelTxConfirm" to "Вы уверены, что хотите отменить эту операцию?",
        "customCurrency" to "Свой символ валюты",
        "customCurrencySymbolLabel" to "Символ валюты (например, $, €, £)",
        "customCurrencyToggle" to "Включить ручной выбор валюты",
        "goalUnset" to "Задайте цель и капитал",
        "toTheGoal" to "до цели",
        "amount" to "Сумма",
        "reason" to "Описание",
        "aboutAppTitle" to "О приложении Копилка",
        "aboutAppText" to "Копилка — это простой помощник по ведению бюджета для отслеживания доходов и расхода.\n\nСоздано Artyomka628 - github.com/artyomka628",
        "inputGoal" to "Сумма цели",
        "inputInitial" to "Текущий баланс",
        "invalidAmount" to "Пожалуйста, введите корректное число",
        "amountTooLarge" to "Слишком большая сумма (макс: 1 000 000 000)",
        "success" to "Успешно!",
        "errorSaving" to "Ошибка при сохранении истории",
        "errorLoading" to "Ошибка при загрузке истории",
        "historySaved" to "История успешно экспортирована",
        "historyLoaded" to "История успешно импортирована",
        "historyEmpty" to "История операций пуста",
        "enterReason" to "Введите описание",
        "confirm" to "Подтвердить",
        "cancel" to "Отмена",
        "statsResetFrequency" to "Интервал сброса статистики",
        "btnResetStatsNow" to "Сбросить статистику сейчас",
        "resetManual" to "Вручную",
        "resetDaily" to "Ежедневно",
        "resetWeekly" to "Еженедельно",
        "resetMonthly" to "Ежемесячно",
        "hideGoalProgress" to "Скрыть прогресс цели",
        "showMoreColors" to "Больше цветов",
        "showLessColors" to "Меньше цветов",
        "themeTitle" to "Цвет темы приложения",
        "themeViolet" to "Фиолетовый (По умолчанию)",
        "themeTeal" to "Бирюзовый",
        "themeAmber" to "Янтарный",
        "themeEmerald" to "Изумрудный",
        "themeRose" to "Розовый",
        "themeBlue" to "Ледяной синий",
        "themeRed" to "Красный",
        "themeIndigo" to "Индиго",
        "themeOrange" to "Оранжевый",
        "themePurple" to "Пурпурный",
        "themeCyan" to "Голубой",
        "themeLime" to "Лаймовый",
        "themePeach" to "Персиковый",
        "themeMint" to "Мятный",
        "themeLavender" to "Лавандовый",
        "themeSky" to "Небесно-голубой",
        "themeMagenta" to "Пурпурно-розовый",
        "themeGold" to "Золотой",
        "themeSapphire" to "Сапфировый",
        "themeBronze" to "Бронзовый",
        "themeMaterialYou" to "Цвет системы (Material You)",
        "themeCustom" to "Свой цвет",
        "customColorPicker" to "Выбор цвета (RGB)",
        "customAppIconSettings" to "Настройки иконки приложения",
        "launcherIconColor" to "Цвет иконки на рабочем столе",
        "matchAppTheme" to "Как в приложении",
        "matchSystem" to "Из системы (Material You)",
        "appIconSymbolTitle" to "Символ валюты на иконке",
        "appIconSymbolDesc" to "Кастомный символ отображается в углу экрана.",
        "applyIconBtn" to "Применить иконку",
        "applyIconSuccess" to "Иконка успешно применена! Лаунчер обновлен.",
        "appVersion" to "Версия приложения",
        "checkForUpdates" to "Проверить обновления",
        "updateAvailable" to "Доступно обновление!",
        "upToDate" to "У вас установлена последняя версия",
        "downloadUpdate" to "Скачать обновление",
        "checkingUpdates" to "Проверка обновлений...",
        "errorCheckingUpdates" to "Ошибка проверки обновлений"
    )

    fun getString(key: String, language: AppLanguage): String {
        return if (language == AppLanguage.RU) {
            ruStrings[key] ?: enStrings[key] ?: key
        } else {
            enStrings[key] ?: key
        }
    }
}
